/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/** npx gltfjsx boschbetonV101.glb */

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
// import { LoopOnce } from "three";

export default function Model({ ...props }) {
  const [n, setN] = useState(-0.76)
  const group = useRef();
  const wallRight = useRef();
  const sidRight = useRef();

  const { nodes, materials } = useGLTF("/boschbetonV101.glb");

  const createSideLoop =()=> {
    let side = [];
    for (var i = 0; i < props.loop; i++) {
      var z = i;      
      side[i] = [z];
    }
    return side;
  }

  const sides = createSideLoop().map(
    (cords, i) => {
      return (
        <>
          <mesh
          ref={sidRight}
          key={`right-${i}`}
            geometry={nodes["sid-right"].geometry}
            material={nodes["sid-right"].material}
            position={[2.77, 0.74, cords*-1]}
          />
          <mesh
          // key={`left-${i}`}
            geometry={nodes["sid-left"].geometry}
            material={nodes["sid-left"].material}
            position={[-4.73, 0.74, cords*-1]}
            rotation={[-Math.PI, 1.57, -Math.PI]}
          />
        </>
      );
    }    
  );

  setN(sidRight.current.position.z)
if(wallRight.current != undefined){
  console.log('wallRight: ',wallRight.current.position.z);
} 
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.car001.geometry}
        material={materials.Material}
        position={[-0.14, 1.06, 0.11]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      {sides}

      <mesh
        geometry={nodes.flour001.geometry}
        material={nodes.flour001.material}
        position={[23.27, 0.24, -39.93]}
      />
      <mesh
        geometry={nodes["rear-wall-midel"].geometry}
        material={nodes["rear-wall-midel"].material}
        position={[-0.93, 0.75, -0.71]}
      />
      <mesh
        geometry={nodes["rear-wall-left"].geometry}
        material={nodes["rear-wall-left"].material}
        position={[-3.86, 0.75, -0.71]}
      />
      {/* <mesh
        geometry={nodes["rear-wall-left"].geometry}
        material={nodes["rear-wall-left"].material}
        position={[-3.86, 0.75, -0.71]}
      /> */}
      <mesh
      ref={wallRight}
        geometry={nodes["rear-Wall-right"].geometry}
        material={nodes["rear-Wall-right"].material}
        // position={[1.99, 0.75, { n ? n : -0.76}]} error need to fix
      />
    </group>
  );
}

useGLTF.preload("/boschbetonV101.glb");
