/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/mbs-Beton.glb");
  console.log("materials: ", materials.back.color);
  console.log("materials: ", materials.back.color);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[-4.5, 0, 2.5]}
      rotation={[0, -Math.PI / 2, -0.9]}
    >
      <mesh
        geometry={nodes.Text.geometry}
        // material={materials.back}
        material={new THREE.MeshBasicMaterial({ color: "black" })}
        // material-color="red"
        // materialcolor={"red"}
        material-roughness={[0.2]}
        material-metalness={[0]}
        position={[-0.29, 0, 0.2]}
        rotation={[3.1, 1.57, -3.11]}
        // rotation={[3.1, 1.57, -3.11]}
      />
      <mesh
        geometry={nodes.red.geometry}
        // material={materials.red}
        material={new THREE.MeshBasicMaterial({ color: 0xce2613 })}
        material-color={"red"}
        material-roughness={[0]}
        material-metalness={[1]}
        position={[-0.34, 0, 0.35]}
      />
      <mesh
        geometry={nodes.green.geometry}
        // material={materials.green}
        material={new THREE.MeshBasicMaterial({ color: 0x00611b })}
        // material-color={"green"}
        material-roughness={[1]}
        position={[-0.34, 0, 0.64]}
        rotation={[-Math.PI, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/mbs-Beton.glb");
