/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function RearWall({ ...props }) {
  const group = useRef();

  const { nodes, materials } = useGLTF("/boschbetonV101.glb");

  return (
    <group ref={group} {...props} dispose={null} visible={props.visible}>
      <mesh
        geometry={nodes["rear-wall-midel"].geometry}
        material={nodes["rear-wall-midel"].material}
        position={[-0.93 + props.poX / 2, 0.75, -0.71 - props.poZ + 1]}
        scale={[Math.floor(props.poX / 2 + 1), 1, 1]}
        // scale={[props.poX > 0 ? Math.trunc(props.poX / 2) : 1, 1, 1]}
      />
      <mesh
        geometry={nodes["rear-wall-left"].geometry}
        material={nodes["rear-wall-left"].material}
        position={[-3.86, 0.75, -0.71 - props.poZ + 1]}
      />
      <mesh
        geometry={nodes["rear-Wall-right"].geometry}
        material={nodes["rear-Wall-right"].material}
        position={[1.99 + props.poX, 0.75, -0.76 - props.poZ + 1]}
      />
    </group>
  );
}

useGLTF.preload("/boschbetonV101.glb");
